name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.2.1
  cupertino_icons: ^1.0.8
  url_launcher: 6.3.2
  google_fonts: ^6.2.1
  firebase_core: 4.1.0
  firebase_auth: 6.0.2
  google_sign_in: 6.2.1
  flutter_facebook_auth: ^7.1.2
  audioplayers: 6.5.1
  table_calendar: ^3.0.9
  intl: ^0.20.2
  mysql1: ^0.20.0
  http: 1.5.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/picture/bg.jpg
    - assets/picture/login.png
    - assets/picture/register.png
    - assets/picture/home.png
    - assets/picture/diary.jpg
    - assets/picture/recommendation.jpg
    - assets/picture/chatbot.png
    - assets/picture/breathing.jpg
    - assets/picture/setting.jpg
    - assets/picture/fullleaf.png
    - assets/picture/halfleaf.png
    - assets/picture/flyleaf.png
    - assets/icons/fb.png
    - assets/icons/google.png
    - assets/breath/breathing_guide.mp4
    - assets/breath/intro.mp3
    - assets/breath/guide.mp3
    - assets/scenario_music/relaxing-smoothed-brown-noise.mp3
    - assets/scenario_music/soft-brown-noise-.mp3
    - assets/scenario_music/soothing-deep-noise-.mp3
    - assets/scenario_music/rain-on-window-white-noise.mp3
    - assets/scenario_music/taiwan-blue-magpie-dawn-calls.mp3
    - assets/oils/1.jpg
    - assets/oils/2.jpg
    - assets/oils/3.jpg
    - assets/oils/4.jpg
    - assets/oils/5.jpg
    - assets/oils/6.jpg
    - assets/oils/7.jpg
    - assets/oils/8.jpg
    - assets/oils/9.jpg
    - assets/oils/10.jpg
    - assets/oils/11.jpg
    - assets/oils/12.jpg
    - assets/oils/13.jpg
    - assets/oils/14.jpg
    - assets/oils/15.jpg
    - assets/oils/16.jpg
    - assets/oils/17.jpg
    - assets/oils/18.jpg
    - assets/oils/19.jpg
    - assets/oils/20.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/smiley2.png"
  min_sdk_android: 21
