name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9  
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.9 
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  audioplayers: ^6.5.0
  table_calendar: ^3.0.9
  intl: ^0.19.0
  mysql1: ^0.20.0
  http: ^1.1.0
  shared_preferences: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/picture/bg.jpg
    - assets/picture/login.png
    - assets/picture/register.png
    - assets/picture/home.png
    - assets/picture/diary.jpg
    - assets/picture/recommendation.jpg
    - assets/picture/chatbot.png
    - assets/picture/breathing.jpg
    - assets/picture/setting.jpg
    - assets/icons/fb.png
    - assets/icons/google.png
    - assets/icons/interface_loading_circle.svg
    - assets/icons/interface_navigation_left_circle.svg
    - assets/breath/breathing_guide.mp4
    - assets/breath/intro.mp3
    - assets/breath/guide.mp3
    - assets/scenario_music/relaxing-smoothed-brown-noise.mp3
    - assets/scenario_music/soft-brown-noise-.mp3
    - assets/scenario_music/soothing-deep-noise-.mp3
    - assets/oils/1.jpg
    - assets/oils/2.jpg
    - assets/oils/3.jpg
    - assets/oils/4.jpg
    - assets/oils/5.jpg
    - assets/oils/6.jpg
    - assets/oils/7.jpg
    - assets/oils/8.jpg
    - assets/oils/9.jpg
    - assets/oils/10.jpg
    - assets/oils/11.jpg
    - assets/oils/12.jpg
    - assets/oils/13.jpg
    - assets/oils/14.jpg
    - assets/oils/15.jpg
    - assets/oils/16.jpg
    - assets/oils/17.jpg
    - assets/oils/18.jpg
    - assets/oils/19.jpg
    - assets/oils/20.jpg
  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/pixel.ttf 