// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK6JD3GSe2jCFSwH7uEYBoutWCHgzW0es',
    appId: '1:483152981384:web:f470578f090457aa559e3d',
    messagingSenderId: '483152981384',
    projectId: 'smaily2app',
    authDomain: 'smaily2app.firebaseapp.com',
    storageBucket: 'smaily2app.firebasestorage.app',
    measurementId: 'G-WSRZZZ74K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_omKNwRlJ5_EE5i62zIEGHQ9bofAKw8',
    appId: '1:483152981384:android:a804de88a009e429559e3d',
    messagingSenderId: '483152981384',
    projectId: 'smaily2app',
    storageBucket: 'smaily2app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzFti_m4my502Yc7QMW8-PnnnkPHqUrRo',
    appId: '1:483152981384:ios:31d31a75c93bd059559e3d',
    messagingSenderId: '483152981384',
    projectId: 'smaily2app',
    storageBucket: 'smaily2app.firebasestorage.app',
    iosClientId:
        '483152981384-d9vn8m5olburii9dvomc5bg8id652ph9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzFti_m4my502Yc7QMW8-PnnnkPHqUrRo',
    appId: '1:483152981384:ios:31d31a75c93bd059559e3d',
    messagingSenderId: '483152981384',
    projectId: 'smaily2app',
    storageBucket: 'smaily2app.firebasestorage.app',
    iosClientId:
        '483152981384-d9vn8m5olburii9dvomc5bg8id652ph9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK6JD3GSe2jCFSwH7uEYBoutWCHgzW0es',
    appId: '1:483152981384:web:d6d0ace420993369559e3d',
    messagingSenderId: '483152981384',
    projectId: 'smaily2app',
    authDomain: 'smaily2app.firebaseapp.com',
    storageBucket: 'smaily2app.firebasestorage.app',
    measurementId: 'G-27V8SHF4J0',
  );
}
